version: 2
updates:
- package-ecosystem: npm
  directory: "/generators/app/templates"
  schedule:
    interval: daily
    time: '13:30'
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '13:30'
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '13:30'
  open-pull-requests-limit: 99
