name: Node.js Package

on: [push]
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  build:
    name: Node.js ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.2
        with:
          version: ${{ matrix.node_version }}

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test --if-present

#   publish-npm:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2.3.3
#       - uses: actions/setup-node@v2.1.2
#         with:
#           version: 12
#           registry-url: https://registry.npmjs.org/
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}
